import { ObjectId } from "mongodb";
import { getServerSession } from "next-auth";
import { NextResponse } from "next/server";
import { z } from "zod";
import { FREE_SIGNUP_CREDITS, reserveGenerationCredit, refundGenerationCredit, type UserAccount } from "../../../lib/account";
import { authOptions } from "../../../lib/auth";
import clientPromise from "../../../lib/mongodb";

const requestSchema = z.object({
  figmaLink: z.string().trim().optional(),
  prompt: z.string().trim().min(3, "Describe what you want to build."),
  referenceImage: z
    .object({
      data: z.string().min(1),
      mimeType: z.string().min(1),
      name: z.string().min(1),
    })
    .optional(),
  currentGeneration: z
    .object({
      id: z.string().optional(),
      title: z.string().optional(),
      summary: z.string().optional(),
      prompt: z.string().optional(),
      previewHtml: z.string().optional(),
      previewCss: z.string().optional(),
      previewJs: z.string().optional(),
      files: z
        .array(
          z.object({
            path: z.string().min(1),
            content: z.string(),
          }),
        )
        .optional(),
    })
    .optional(),
});

const generationSchema = z.object({
  title: z.string().min(1),
  summary: z.string().min(1),
  previewHtml: z.string().min(1),
  previewCss: z.string().min(1),
  previewJs: z.string().optional().default(""),
  files: z
    .array(
      z.object({
        path: z.string().min(1),
        content: z.string(),
      }),
    )
    .min(1),
  notes: z.array(z.string()).optional().default([]),
});

const fileChangeSchema = z.object({
  path: z.string().min(1),
  action: z.enum(["created", "edited"]),
});

const WEBSITE_GENERATION_SYSTEM_PROMPT = `SYSTEM PROMPT:
You are an expert senior frontend engineer and product designer. You build beautiful, polished, production-ready React + Tailwind websites. Your output should look like something generated by v0, Lovable, Framer, or a high-end design agency.

For every user request:
- First understand the exact type of website/app requested.
- Choose a strong visual direction.
- Create a design system with colors, typography, spacing, cards, buttons, and layout rules.
- Generate a complete responsive website.
- Use realistic content.
- Use modern Tailwind styling.
- Use icons where useful using CSS, text symbols, or inline-safe shapes; do not import icon packages unless already included.
- Use gradients, glassmorphism, soft shadows, hover states, transitions, and micro-interactions where appropriate.
- Make the UI feel complete and premium.
- Make every section useful and visually intentional.

QUALITY BAR:
The output must not look like a beginner project. It should look like a polished portfolio/demo-worthy product.

Internal design checklist before returning:
- Is the page visually premium?
- Is spacing consistent?
- Is typography modern?
- Are sections complete?
- Are cards populated with real content?
- Are buttons styled properly?
- Is the layout responsive?
- Does the result match the user prompt?
- Does it look better than a basic HTML mockup?

Never generate plain white pages with random boxes, empty cards, unstyled navbars, misaligned sections, placeholder-only text, huge blank spaces, unfinished sections, or single-color rectangles pretending to be components.`;

const PREMIUM_OUTPUT_REQUIREMENTS = `PREMIUM OUTPUT REQUIREMENTS:
- Generate a finished product experience, not a sketch, wireframe, starter screen, or tutorial mockup.
- The first viewport must look impressive immediately and fill the available preview area.
- Use a real visual system: deliberate background, surfaces, borders, shadows, accent color, type scale, spacing rhythm, and hover states.
- Use domain-specific content. Never use generic labels like "Video Title", "Product Name", "Card title", "Feature one", or lorem ipsum.
- Include enough repeated realistic items to feel real: feeds need many posts, video apps need many video cards, stores need many products, dashboards need many metrics/rows, landing pages need complete sections.
- Avoid tiny demos with one card, one section, one centered panel, or lots of empty whitespace.
- Preview markup must be rich enough to judge the result without running React.
- React output and preview output must visually match.
- Prefer tasteful density over sparse emptiness. Use layered sections, split layouts, sidebars, tabs, chips, tables, cards, mockups, and data where appropriate.
- Use responsive layouts that meaningfully change on mobile instead of just shrinking desktop.
- Keep code clean, but prioritize visual completeness and prompt accuracy.`;

const geminiFallbackModels = ["gemini-3.5-flash", "gemini-2.5-flash", "gemini-2.0-flash", "gemini-1.5-flash"];
const maxAiAttemptsPerModel = 1;
const aiRequestTimeoutMs = 120000;

type AiProvider = "gemini" | "openrouter";
type WebsiteType =
  | "saas-landing"
  | "ai-tool-landing"
  | "fashion-ecommerce"
  | "restaurant-cafe"
  | "portfolio"
  | "agency"
  | "video-platform-dashboard"
  | "social-feed"
  | "marketplace"
  | "fintech-landing"
  | "mobile-app-landing"
  | "admin-dashboard"
  | "generic";

type PromptAnalysis = {
  websiteType: WebsiteType;
  visualStyle: string[];
  requiredSections: string[];
  brandName: string;
  targetAudience: string;
  cloneIntent: string;
};


type GeminiResponse = {
  candidates?: Array<{
    content?: {
      parts?: Array<{
        text?: string;
      }>;
    };
  }>;
  error?: {
    message?: string;
  };
};

type OpenRouterResponse = {
  choices?: Array<{
    message?: {
      content?: string | Array<{ type?: string; text?: string }>;
    };
  }>;
  error?: {
    message?: string;
  };
};

export async function POST(request: Request) {
  const session = await getServerSession(authOptions);

  if (!session?.user) {
    return NextResponse.json({ error: "You must be signed in to generate." }, { status: 401 });
  }

  const provider = getAiProvider();
  const apiKey = provider === "openrouter" ? process.env.OPENROUTER_API_KEY : process.env.GEMINI_API_KEY;

  if (!apiKey) {
    return NextResponse.json({ error: `${provider === "openrouter" ? "OpenRouter" : "Gemini"} API key is not configured.` }, { status: 500 });
  }

  const body = await request.json().catch(() => null);
  const parsed = requestSchema.safeParse(body);

  if (!parsed.success) {
    return NextResponse.json({ error: parsed.error.issues[0]?.message ?? "Invalid request." }, { status: 400 });
  }

  const client = await clientPromise;
  const db = client.db();
  const users = db.collection<UserAccount>("users");
  const creditReservation = await reserveGenerationCredit(users, session.user);

  if (!creditReservation) {
    return NextResponse.json({ error: "Account not found." }, { status: 404 });
  }

  if (!creditReservation.ok) {
    return NextResponse.json(
      { error: "You are out of credits. Buy a plan to keep generating.", creditsRemaining: creditReservation.credits, creditLimit: FREE_SIGNUP_CREDITS },
      { status: 402 },
    );
  }

  try {
    const result = enforceGenerationQuality(
      parsed.data.prompt,
      await generateWithAi({
        provider,
        apiKey,
        figmaLink: parsed.data.figmaLink,
        prompt: parsed.data.prompt,
        referenceImage: parsed.data.referenceImage,
        currentGeneration: parsed.data.currentGeneration,
      }),
    );

    const qualityIssues = validateGeneratedQuality(parsed.data.prompt, result);

    if (qualityIssues.length) {
      console.warn(`[Mosaic generation] generated UI quality warnings: ${qualityIssues.join("; ")}`);
    }

    const now = new Date();
    const generationRecord = {
      ...result,
      prompt: parsed.data.prompt,
      figmaLink: parsed.data.figmaLink,
      referenceImageName: parsed.data.referenceImage?.name,
      userId: creditReservation.userId,
      generatedAt: now,
      updatedAt: now,
    };
    const currentGenerationId = parsed.data.currentGeneration?.id;
    let generationId = "";

    if (currentGenerationId && ObjectId.isValid(currentGenerationId)) {
      const updated = await db.collection("generations").findOneAndUpdate(
        { _id: new ObjectId(currentGenerationId), userId: creditReservation.userId },
        { $set: generationRecord },
        { returnDocument: "after", projection: { _id: 1 } },
      );

      generationId = updated.value?._id.toString() ?? "";
    }

    if (!generationId) {
      const saved = await db.collection("generations").insertOne({
        ...generationRecord,
        createdAt: now,
      });
      generationId = saved.insertedId.toString();
    }

    return NextResponse.json({
      generation: result,
      generationId,
      filesChanged: getFileChanges(result.files, parsed.data.currentGeneration?.files ?? []),
      creditsRemaining: creditReservation.credits,
      creditLimit: FREE_SIGNUP_CREDITS,
    });
  } catch (error) {
    await refundGenerationCredit(users, creditReservation.userId);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Generation failed. Please try again." },
      { status: 500 },
    );
  }
}

function getFileChanges(nextFiles: z.infer<typeof generationSchema>["files"], previousFiles: Array<{ path: string; content: string }>) {
  const previousByPath = new Map(previousFiles.map((file) => [file.path, file.content]));

  return nextFiles
    .map((file) => {
      const previousContent = previousByPath.get(file.path);

      if (previousContent === undefined) {
        return { path: file.path, action: "created" as const };
      }

      if (previousContent !== file.content) {
        return { path: file.path, action: "edited" as const };
      }

      return null;
    })
    .filter((fileChange): fileChange is z.infer<typeof fileChangeSchema> => Boolean(fileChange));
}

function enforceGenerationQuality(prompt: string, generation: z.infer<typeof generationSchema>) {
  const qualityIssues = validateGeneratedQuality(prompt, generation);

  if (qualityIssues.length) {
    console.warn(`[Mosaic generation] generated UI quality warnings: ${qualityIssues.join("; ")}`);
  }

  return generation;
}

function validateGeneratedQuality(prompt: string, generation: z.infer<typeof generationSchema>) {
  const content = `${generation.previewHtml} ${generation.previewCss} ${generation.files.map((file) => file.content).join(" ")}`.toLowerCase();
  const issues: string[] = [];
  const sectionCount = (content.match(/<section|section class|function [a-z0-9]+section|const [a-z0-9]+section/gi) ?? []).length;
  const cardSignals = (content.match(/card|article|grid|thumbnail|product|metric|testimonial/g) ?? []).length;
  const repeatedItemSignals = (content.match(/article|post|tweet|video|product|row|metric|testimonial|card|item/g) ?? []).length;
  const hasResponsiveClasses = /\b(sm|md|lg|xl|2xl):/.test(content) || /@media\s*\(/.test(content);
  const hasStyledButton = /button|rounded-full|hover:|transition/.test(content);
  const hasNavigation = /<nav|navitems|navbar|sidebar|topbar|header/.test(content);
  const hasPlaceholderOnlyText = /video title|lorem ipsum|placeholder|card title|product name/i.test(content);
  const isComplexPrompt = /clone|dashboard|analytics|social|video|youtube|twitter|facebook|ecommerce|store|shop|marketplace|app/i.test(prompt);

  if (sectionCount < 4 && !/clone|dashboard|app interface/i.test(prompt)) issues.push("too few meaningful sections");
  if (isComplexPrompt && cardSignals < 10) issues.push("too few repeated cards/items");
  if (isComplexPrompt && repeatedItemSignals < 12) issues.push("too little realistic repeated content");
  if (!hasResponsiveClasses) issues.push("missing responsive Tailwind/media classes");
  if (!hasStyledButton) issues.push("buttons or interactions are under-styled");
  if (!hasNavigation) issues.push("navigation is missing or weak");
  if (hasPlaceholderOnlyText) issues.push("placeholder-only copy detected");
  if (generation.previewHtml.length < 4500 || generation.previewCss.length < 2200) issues.push("preview is too small/basic");

  return issues;
}

async function improveGenerationQuality({
  provider,
  apiKey,
  originalPrompt,
  issues,
  generation,
}: {
  provider: AiProvider;
  apiKey: string;
  originalPrompt: string;
  issues: string[];
  generation: z.infer<typeof generationSchema>;
}) {
  return generateWithAi({
    provider,
    apiKey,
    prompt: [
      originalPrompt,
      "",
      "The UI is too basic. Improve it into a polished production-quality interface with richer layout, better spacing, realistic content, responsive sections, modern visual design, and complete components.",
      `Quality issues to fix: ${issues.join("; ")}`,
      "Return the full updated project JSON with complete files and self-contained preview fields.",
    ].join("\n"),
    currentGeneration: {
      title: generation.title,
      summary: generation.summary,
      prompt: originalPrompt,
      previewHtml: generation.previewHtml,
      previewCss: generation.previewCss,
      previewJs: generation.previewJs,
      files: generation.files,
    },
  });
}

async function generateWithAi(input: {
  provider: AiProvider;
  apiKey: string;
  figmaLink?: string;
  prompt: string;
  referenceImage?: { data: string; mimeType: string; name: string };
  currentGeneration?: z.infer<typeof requestSchema>["currentGeneration"];
}) {
  if (input.provider === "openrouter") {
    return generateWithOpenRouter(input);
  }

  return generateWithGemini(input);
}

async function generateWithOpenRouter({
  apiKey,
  figmaLink,
  prompt,
  referenceImage,
  currentGeneration,
}: {
  apiKey: string;
  figmaLink?: string;
  prompt: string;
  referenceImage?: { data: string; mimeType: string; name: string };
  currentGeneration?: z.infer<typeof requestSchema>["currentGeneration"];
}) {
  const baseUrl = (process.env.OPENROUTER_BASE_URL?.trim() || "https://openrouter.ai/api/v1").replace(/\/+$/, "");
  const model = process.env.OPENROUTER_MODEL?.trim() || "openrouter/free";
  const promptText = extractGeminiPromptText(createGeminiPayload({ figmaLink, prompt, referenceImage, currentGeneration }));
  const errors: string[] = [];

  for (let attempt = 1; attempt <= maxAiAttemptsPerModel; attempt += 1) {
    let response: Response;

    try {
      response = await fetchWithTimeout(`${baseUrl}/chat/completions`, {
        method: "POST",
        headers: {
          Authorization: `Bearer ${apiKey}`,
          "Content-Type": "application/json",
          "HTTP-Referer": process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000",
          "X-Title": "Mosaic",
        },
        body: JSON.stringify({
          model,
          temperature: 0.5,
          top_p: 0.9,
          max_tokens: Number(process.env.OPENROUTER_MAX_TOKENS ?? 16000),
          response_format: { type: "json_object" },
          messages: [
            {
              role: "system",
              content: `${WEBSITE_GENERATION_SYSTEM_PROMPT}\n\n${PREMIUM_OUTPUT_REQUIREMENTS}\n\nReturn only valid JSON. No markdown. No explanations.`,
            },
            {
              role: "user",
              content: referenceImage
                ? [
                    { type: "text", text: promptText },
                    {
                      type: "image_url",
                      image_url: {
                        url: `data:${referenceImage.mimeType};base64,${referenceImage.data}`,
                      },
                    },
                  ]
                : promptText,
            },
          ],
        }),
      });
    } catch (error) {
      const message = error instanceof Error ? error.message : "OpenRouter request timed out";
      errors.push(`${model}: ${message}`);

      if (attempt < maxAiAttemptsPerModel) {
        await wait(900 * attempt);
        continue;
      }

      break;
    }

    const data = (await response.json().catch(() => null)) as OpenRouterResponse | null;

    if (!response.ok) {
      const message = data?.error?.message ?? `OpenRouter returned ${response.status}`;
      errors.push(`${model}: ${message}`);

      if (attempt < maxAiAttemptsPerModel && isTemporaryAiError(response.status, message)) {
        await wait(900 * attempt);
        continue;
      }

      break;
    }

    const content = data?.choices?.[0]?.message?.content;
    const text = Array.isArray(content) ? content.map((part) => part.text ?? "").join("\n").trim() : content?.trim();

    if (!text) {
      errors.push(`${model}: returned an empty response`);
      break;
    }

    return parseGeneration(text);
  }

  if (errors.some((error) => isTemporaryAiError(undefined, error))) {
    throw new Error("OpenRouter is temporarily unavailable. Please run it again in a minute.");
  }

  throw new Error(errors[0] ?? "OpenRouter did not return a usable generation.");
}

async function generateWithGemini({
  apiKey,
  figmaLink,
  prompt,
  referenceImage,
  currentGeneration,
}: {
  apiKey: string;
  figmaLink?: string;
  prompt: string;
  referenceImage?: { data: string; mimeType: string; name: string };
  currentGeneration?: z.infer<typeof requestSchema>["currentGeneration"];
}) {
  const preferredModel = process.env.GEMINI_MODEL?.trim();
  const models = Array.from(new Set([preferredModel, ...geminiFallbackModels].filter(Boolean))) as string[];
  const payload = createGeminiPayload({ figmaLink, prompt, referenceImage, currentGeneration });
  const errors: string[] = [];

  for (const model of models) {
    for (let attempt = 1; attempt <= maxAiAttemptsPerModel; attempt += 1) {
      let response: Response;

      try {
        response = await fetchWithTimeout(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "x-goog-api-key": apiKey,
          },
          body: JSON.stringify(payload),
        });
      } catch (error) {
        const message = error instanceof Error ? error.message : `${model} request timed out`;
        errors.push(`${model}: ${message}`);

        if (attempt < maxAiAttemptsPerModel) {
          await wait(900 * attempt);
          continue;
        }

        break;
      }

      const data = (await response.json().catch(() => null)) as GeminiResponse | null;

      if (!response.ok) {
        const message = data?.error?.message ?? `${model} returned ${response.status}`;
        errors.push(`${model}: ${message}`);

        if (attempt < maxAiAttemptsPerModel && isTemporaryAiError(response.status, message)) {
          await wait(900 * attempt);
          continue;
        }

        break;
      }

      const text = data?.candidates?.[0]?.content?.parts?.map((part) => part.text ?? "").join("\n").trim();

      if (!text) {
        errors.push(`${model}: returned an empty response`);
        break;
      }

      return parseGeneration(text);
    }
  }

  if (errors.some((error) => isTemporaryAiError(undefined, error))) {
    throw new Error("Gemini is temporarily overloaded. I tried the available fallback models, but they are busy right now. Please run it again in a minute.");
  }

  throw new Error(errors[0] ?? "Gemini did not return a usable generation.");
}

function createGeminiPayload({
  figmaLink,
  prompt,
  referenceImage,
  currentGeneration,
}: {
  figmaLink?: string;
  prompt: string;
  referenceImage?: { data: string; mimeType: string; name: string };
  currentGeneration?: z.infer<typeof requestSchema>["currentGeneration"];
}) {
  const cloneGuidance = getCloneGuidance(prompt);
  const promptAnalysis = analyzePrompt(prompt);
  const enhancedBrief = enhanceUserPrompt(prompt);
  const currentProjectContext = currentGeneration
    ? [
        "",
        "Existing project context for a follow-up edit:",
        `Current id: ${currentGeneration.id ?? "none"}`,
        `Current title: ${currentGeneration.title ?? "Untitled"}`,
        `Original/previous prompt: ${currentGeneration.prompt ?? "none"}`,
        `Current summary: ${currentGeneration.summary ?? "none"}`,
        "When existing project context is provided, treat the user prompt as an edit request. Preserve the existing app concept, pages, layout, content, interactions, responsiveness, and file structure unless the user explicitly asks to replace them.",
        "Return the FULL updated project JSON, not a patch. Include every required file with complete updated contents.",
        "Current previewHtml:",
        truncateForPrompt(currentGeneration.previewHtml ?? "", 9000),
        "Current previewCss:",
        truncateForPrompt(currentGeneration.previewCss ?? "", 9000),
        currentGeneration.previewJs ? `Current previewJs:\n${truncateForPrompt(currentGeneration.previewJs, 4500)}` : "Current previewJs: none",
        "Current files:",
        serializeFilesForPrompt(currentGeneration.files ?? []),
      ].join("\n")
    : "";

  return {
    generationConfig: {
      temperature: 0.5,
      topP: 0.9,
      maxOutputTokens: Number(process.env.GEMINI_MAX_OUTPUT_TOKENS ?? 16000),
      responseMimeType: "application/json",
    },
    contents: [
      {
        role: "user",
        parts: [
          {
            text: [
              WEBSITE_GENERATION_SYSTEM_PROMPT,
              PREMIUM_OUTPUT_REQUIREMENTS,
              "Return ONLY valid JSON with this shape:",
              '{"title":"string","summary":"string","previewHtml":"string","previewCss":"string","previewJs":"string","files":[{"path":"string","content":"string"}],"notes":["string"]}',
              "First infer the product type, target audience, and primary user action. Then build a complete, realistic React + Tailwind website, app screen, dashboard, landing page, or mini-flow based on the user request.",
              "Respect the user's requested product identity. Do not rebrand requested products as Mosaic, MosaicTube, MonoAI, or any other house brand unless the user explicitly asks for that.",
              "If the user asks for a clone, remake the recognizable product pattern as closely as possible within React/Tailwind: layout, navigation, spacing, colors, page density, content types, and core interactions should match the referenced product.",
              "For well-known product clone requests, keep the requested product name in visible UI copy when the user uses that name. Example: a YouTube clone should look like YouTube, say YouTube where appropriate, use video feed/sidebar/top search/player patterns, and should not become MosaicTube.",
              "Do not make a shallow or tiny mockup. For clone requests, include enough visible real estate and realistic repeated content to feel like the actual app: sidebars, top bars, cards/lists, filters/tabs, empty/loading states, and responsive mobile behavior.",
              "For social/feed clone requests, build the actual product shell: desktop sidebar, main composer/feed, right trends/suggestions column, mobile bottom nav, many realistic posts, handles, avatars, timestamps, replies, reposts, likes, and interaction buttons.",
              "For video platform clone requests, include a sticky topbar, search, sidebar, category chips, at least 12 realistic video cards, thumbnail art made with CSS gradients, channel avatars, durations, views, and upload times.",
              "For dashboards, include at least 4 metric cards, a CSS chart, activity feed, filters, and a populated table with realistic rows.",
              "For ecommerce, include at least 8 products, category chips, product cards with prices, badges, ratings, cart actions, trust cues, testimonials, FAQ, and footer.",
              "For landing/marketing pages, include at least 6 meaningful sections: navbar, hero, proof/stat strip, feature grid, workflow/product preview, pricing or use cases, testimonials/FAQ, and footer.",
              "For ecommerce/fashion prompts, create a premium brand experience with a clean navbar, luxury hero, product grid, category cards, collection section, editorial lookbook, brand story, testimonials, newsletter signup, and footer.",
              "The files array must represent a proper Vite React project folder structure.",
              "Always include at least these files: package.json, index.html, src/main.jsx, src/App.jsx, src/index.css, tailwind.config.js, postcss.config.js, README.md.",
              "If the app naturally has multiple pages or major views, implement real in-app navigation in src/App.jsx using route state or hash navigation, and include matching links in previewHtml with href values like /, #pricing, #settings, or #dashboard.",
              "The previewHtml navigation links must correspond to visible sections or views so an external page selector can activate them.",
              "Use package.json dependencies compatible with a standard Vite React Tailwind project: react, react-dom, @vitejs/plugin-react, vite, tailwindcss 3.x, postcss, and autoprefixer.",
              "Use React and Tailwind CSS only. Use Tailwind utility classes throughout the React components. Keep custom CSS minimal and only for base styles, keyframes, or small animations.",
              "Design quality is as important as functionality. Prioritize spacing, typography, hierarchy, alignment, visual balance, and responsive polish.",
              "Mobile-first responsive design is required. Every layout must work on mobile, tablet, and desktop.",
              "Use max-w-7xl or equivalent max-width containers for major sections. Use generous whitespace, balanced sections, intelligent grids, and consistent alignment.",
              "Prefer large typography and strong hierarchy: text-4xl through text-7xl for major headings when appropriate, with readable body copy and clear secondary text.",
              "Prefer p-6, p-8, p-10, p-12; gap-6, gap-8, gap-10; rounded-xl, rounded-2xl, rounded-3xl; subtle borders; shadow-md/shadow-lg; and restrained premium gradients.",
              "Avoid cramped p-2 layouts, tiny text, default-looking buttons, generic boxy cards, outdated styling, excessive text density, and beginner tutorial aesthetics.",
              "Use modern card-based UI patterns where useful. Every section should feel intentionally designed rather than templated.",
              "Add hover states, focus states, transitions, micro-interactions, loading/empty states where appropriate, and accessibility considerations such as semantic elements, aria labels, visible focus, and sufficient contrast.",
              "Use realistic mock content and domain-specific details instead of lorem ipsum.",
              "Write reusable React components with clean names and minimal duplication. Separate major sections into components when appropriate.",
              "Do not use remote images, iframes, backend calls, or paid libraries. Use local gradients, SVG, CSS, and realistic placeholder data.",
              "Never output broken image placeholders. If a thumbnail, avatar, logo, or media image is needed, create it with CSS gradients, inline SVG, emoji-free lettermarks, or data-safe markup instead of <img src> values that may fail.",
              "previewHtml/previewCss/previewJs must be a self-contained static preview of the generated app for an iframe. It should visually match the React output.",
              "CRITICAL PREVIEW RULES: previewHtml must contain visible body markup, not an empty #root element, not JSX, and not a full HTML document. Do not include html/head/body/style/script tags in previewHtml.",
              "CRITICAL PREVIEW QUALITY: previewHtml should usually be at least 4500 characters and previewCss at least 2500 characters unless the user explicitly asks for something tiny. A shorter response is usually too basic.",
              "previewCss must be ordinary browser CSS without @tailwind directives or style tags. previewJs must be plain browser JavaScript without imports, exports, JSX, TypeScript, or script tags.",
              "The preview may use Tailwind utility classes because the preview iframe loads Tailwind CDN, but include enough visible markup that it renders immediately without React.",
              "The generated React code should be clean, componentized when useful, accessible, responsive, and ready to run with npm install && npm run dev.",
              "Before returning JSON, self-review spacing, typography hierarchy, responsiveness, visual polish, accessibility, and whether any section feels generic. Upgrade weak sections until the result feels production-ready for paying customers.",
              "If the UI is too basic, improve it before responding: richer layout, better spacing, realistic content, responsive sections, modern visual design, and complete components.",
              "For follow-up edit requests like changing font size, colors, spacing, copy, sections, responsiveness, or component behavior, update the existing project directly and keep everything else stable.",
              cloneGuidance,
              "Avoid markdown fences. Avoid explanations outside JSON.",
              currentProjectContext,
              "",
              `User prompt: ${prompt}`,
              `Prompt analysis: ${JSON.stringify(promptAnalysis)}`,
              `Enhanced build brief: ${enhancedBrief}`,
              figmaLink ? `Figma/reference link: ${figmaLink}` : "Figma/reference link: none provided",
              referenceImage
                ? `Reference image attached: ${referenceImage.name}. Use it as visual guidance for layout, spacing, typography, colors, and cloning the design when requested.`
                : "Reference image attached: none",
            ].join("\n"),
          },
          ...(referenceImage
            ? [
                {
                  inline_data: {
                    data: referenceImage.data,
                    mime_type: referenceImage.mimeType,
                  },
                },
              ]
            : []),
        ],
      },
    ],
  };
}

function extractGeminiPromptText(payload: ReturnType<typeof createGeminiPayload>) {
  const part = payload.contents[0]?.parts[0];
  return part && "text" in part ? part.text : "";
}

function analyzePrompt(prompt: string): PromptAnalysis {
  const normalizedPrompt = prompt.toLowerCase();
  const brandName = extractBrandName(prompt);
  const cloneIntent = getCloneIntent(prompt);
  const websiteType = getWebsiteTypeFromPrompt(normalizedPrompt, cloneIntent);
  const visualStyle = getVisualStyleFromPrompt(normalizedPrompt, websiteType);
  const requiredSections = getRequiredSectionsForType(websiteType);
  const targetAudience = getTargetAudienceForType(websiteType);

  return { websiteType, visualStyle, requiredSections, brandName, targetAudience, cloneIntent };
}

function getDesignInspiration(analysis: PromptAnalysis) {
  if (process.env.DESIGN_SEARCH_ENABLED?.toLowerCase() !== "true" || !process.env.DESIGN_SEARCH_API_KEY) {
    return "";
  }

  const query = `${analysis.visualStyle.join(" ")} ${analysis.websiteType.replace(/-/g, " ")} website design inspiration`;
  return `Optional design search is configured. Use inspiration query "${query}" only for high-level layout and visual direction; do not copy code or proprietary template assets.`;
}

function buildEnhancedDesignBrief(prompt: string, analysis: PromptAnalysis, inspiration: string) {
  return [
    `Build a polished ${analysis.websiteType.replace(/-/g, " ")} for this request: ${prompt}.`,
    analysis.brandName ? `Use the brand name "${analysis.brandName}" prominently and consistently.` : "Create a fitting brand name only if the user did not provide one.",
    analysis.cloneIntent ? `Clone intent: create a polished ${analysis.cloneIntent}-inspired interface without copying protected assets or external code.` : "",
    `Target audience: ${analysis.targetAudience}.`,
    `Visual style: ${analysis.visualStyle.join(", ")}.`,
    `Suggested sections/components: ${analysis.requiredSections.join(", ")}.`,
    inspiration,
    "If this is an app, dashboard, marketplace, or clone request, render the actual application interface instead of a marketing landing page.",
    "Make the result feel populated and usable on first load: realistic data, multiple states, clear navigation, and enough repeated items to judge the product.",
    "Generate a fresh full React + Tailwind implementation and a matching self-contained preview. Do not output a wireframe. Do not output placeholder-only cards. Use populated data arrays and reusable components where useful.",
  ]
    .filter(Boolean)
    .join("\n");
}

function enhanceUserPrompt(prompt: string) {
  const analysis = analyzePrompt(prompt);
  const inspiration = getDesignInspiration(analysis);
  const buildBrief = buildEnhancedDesignBrief(prompt, analysis, inspiration);
  const normalizedPrompt = prompt.toLowerCase();
  const brandName = analysis.brandName;

  if (/yt|youtube/.test(normalizedPrompt) && /clone|app|platform|dashboard/.test(normalizedPrompt)) {
    return `${buildBrief}\nBuild a polished YouTube-inspired video platform dashboard with a sticky top navbar, left sidebar navigation, search bar, category chips, responsive video grid, realistic thumbnail cards, duration badges, channel avatars, video titles, creators, views, upload time, hover states, dark premium surfaces, dense desktop layout, and mobile layout.`;
  }

  if (isFashionBrandPrompt(prompt)) {
    return `${buildBrief}\nBuild a premium modern fashion ecommerce landing page for a clothing brand${brandName ? ` called ${brandName}` : ""} with an elegant navbar, luxury hero section, collection highlights, product cards, category tiles, editorial lookbook, brand story, testimonials, newsletter signup, and footer. Use refined typography, soft gradients, high-quality spacing, responsive grids, polished Tailwind styling, realistic product copy, and a premium brand atmosphere.`;
  }

  if (/shop|store|ecommerce|e-commerce|product|cart|checkout/.test(normalizedPrompt)) {
    return `${buildBrief}\nBuild a premium ecommerce storefront with a polished navbar, hero, category chips, product grid, featured collection, trust badges, testimonials, newsletter, and footer. Use realistic products, prices, merchandising copy, responsive layouts, hover states, and modern Tailwind styling.`;
  }

  if (/dashboard|analytics|admin|crm|chart|metrics/.test(normalizedPrompt)) {
    return `${buildBrief}\nBuild a production-quality SaaS dashboard with sidebar navigation, topbar, metric cards, fake charts built with CSS, activity feed, customer table, filters, responsive layout, hover states, and realistic operating data.`;
  }

  if (/portfolio|personal|resume|designer|developer|creator/.test(normalizedPrompt)) {
    return `${buildBrief}\nBuild a polished portfolio website with a strong hero, selected work grid, services/process section, case-study cards, testimonials, contact CTA, footer, responsive layout, and refined editorial typography.`;
  }

  if (prompt.trim().split(/\s+/).length <= 8) {
    return `${buildBrief}\nBuild a polished, production-quality responsive website for: ${prompt}. Include a premium hero, clear navigation, complete sections, realistic content, strong visual hierarchy, responsive grids, styled buttons, hover states, subtle gradients, cards with depth, and a footer.`;
  }

  return buildBrief;
}

function extractBrandName(prompt: string) {
  const match = prompt.match(/\b(?:called|named|brand\s+called|brand\s+named)\s+["']?([a-zA-Z0-9][a-zA-Z0-9\s-]{1,32})["']?/i);

  if (!match?.[1]) {
    return "";
  }

  return match[1]
    .replace(/\b(?:with|for|that|website|site|landing|page|store|shop|brand|clothing|fashion)\b.*$/i, "")
    .trim();
}

function getCloneIntent(prompt: string) {
  const normalizedPrompt = prompt.toLowerCase();

  if (/youtube|yt\b/.test(normalizedPrompt)) return "YouTube";
  if (/twitter|x clone|tweet/.test(normalizedPrompt)) return "Twitter/X";
  if (/airbnb|booking marketplace|rental/.test(normalizedPrompt)) return "Airbnb";
  if (/facebook|instagram|tiktok|social/.test(normalizedPrompt)) return "social network";

  return /clone|replica|copy|same as/.test(normalizedPrompt) ? "product clone" : "";
}

function getWebsiteTypeFromPrompt(prompt: string, cloneIntent: string): WebsiteType {
  if (/youtube|yt\b|video|streaming|channel|shorts/.test(prompt)) return "video-platform-dashboard";
  if (/twitter|x clone|tweet|social|feed|facebook|instagram|tiktok/.test(prompt)) return "social-feed";
  if (/airbnb|marketplace|booking|rental|travel stay|property/.test(prompt)) return "marketplace";
  if (/clothing|fashion|apparel|streetwear|boutique|wear|garment|collection/.test(prompt)) return "fashion-ecommerce";
  if (/cafe|coffee|restaurant|bistro|bakery|brunch|diner|food|menu/.test(prompt)) return "restaurant-cafe";
  if (/dashboard|admin|analytics|crm|metrics|chart|table/.test(prompt)) return "admin-dashboard";
  if (/portfolio|resume|personal|designer|developer|creator|photographer/.test(prompt)) return "portfolio";
  if (/agency|studio|creative|service business/.test(prompt)) return "agency";
  if (/fintech|finance|bank|payment|wallet|invest/.test(prompt)) return "fintech-landing";
  if (/mobile app|ios|android|app landing/.test(prompt)) return "mobile-app-landing";
  if (/ai|chatbot|automation|agent/.test(prompt)) return "ai-tool-landing";
  if (cloneIntent) return "generic";
  return "saas-landing";
}

function isFashionBrandPrompt(prompt: string) {
  return /clothing|fashion|apparel|streetwear|boutique|wear|garment|collection/i.test(prompt);
}

function getVisualStyleFromPrompt(prompt: string, websiteType: WebsiteType) {
  const styles = new Set<string>();

  if (/dark|black|neon|cyber/.test(prompt)) styles.add("dark");
  if (/luxury|premium|elegant|minimal/.test(prompt)) styles.add("luxury");
  if (/playful|fun|colorful/.test(prompt)) styles.add("playful");
  if (/futuristic|ai|glass/.test(prompt)) styles.add("futuristic");
  if (/editorial|magazine|fashion/.test(prompt)) styles.add("editorial");

  const defaults: Record<WebsiteType, string[]> = {
    "saas-landing": ["startup", "premium", "minimal"],
    "ai-tool-landing": ["futuristic", "glassmorphism", "premium"],
    "fashion-ecommerce": ["luxury", "minimal", "editorial"],
    "restaurant-cafe": ["warm", "editorial", "hospitality"],
    portfolio: ["editorial", "minimal", "personal"],
    agency: ["bold", "creative", "premium"],
    "video-platform-dashboard": ["modern", "dashboard", "media"],
    "social-feed": ["dark", "social", "dense"],
    marketplace: ["clean", "marketplace"],
    "fintech-landing": ["trustworthy", "premium", "data"],
    "mobile-app-landing": ["consumer", "polished", "playful"],
    "admin-dashboard": ["operational", "dense", "dark"],
    generic: ["premium", "responsive"],
  };

  defaults[websiteType].forEach((style) => styles.add(style));
  return [...styles].slice(0, 5);
}

function getRequiredSectionsForType(websiteType: WebsiteType) {
  const sections: Record<WebsiteType, string[]> = {
    "saas-landing": ["navbar", "hero", "features", "workflow", "pricing", "faq", "footer"],
    "ai-tool-landing": ["navbar", "hero", "prompt-console", "capabilities", "workflow", "use-cases", "footer"],
    "fashion-ecommerce": ["navbar", "hero", "collections", "product-grid", "lookbook", "testimonials", "footer"],
    "restaurant-cafe": ["navbar", "hero", "hours", "menu", "story", "visit", "footer"],
    portfolio: ["navbar", "hero", "selected-work", "services", "process", "contact", "footer"],
    agency: ["navbar", "hero", "services", "case-studies", "process", "contact", "footer"],
    "video-platform-dashboard": ["topbar", "sidebar", "category-tabs", "video-grid", "video-card", "shorts-row"],
    "social-feed": ["sidebar", "timeline", "composer", "trends", "who-to-follow", "mobile-tabs"],
    marketplace: ["navbar", "search", "filters", "listing-grid", "detail-cards", "footer"],
    "fintech-landing": ["navbar", "hero", "stats", "product-preview", "security", "features", "footer"],
    "mobile-app-landing": ["navbar", "hero", "phone-mockup", "features", "reviews", "download-cta", "footer"],
    "admin-dashboard": ["sidebar", "topbar", "metrics", "chart", "activity", "table", "filters"],
    generic: ["navbar", "hero", "content", "features", "footer"],
  };

  return sections[websiteType];
}

function getTargetAudienceForType(websiteType: WebsiteType) {
  const audiences: Record<WebsiteType, string> = {
    "saas-landing": "startup buyers and product teams",
    "ai-tool-landing": "teams evaluating AI workflow tools",
    "fashion-ecommerce": "style-conscious shoppers and fashion brand visitors",
    "restaurant-cafe": "local guests, brunch customers, and coffee regulars",
    portfolio: "clients, recruiters, and collaborators",
    agency: "brands looking for creative or technical services",
    "video-platform-dashboard": "video viewers and creators",
    "social-feed": "community members and content creators",
    marketplace: "buyers browsing listings and hosts/sellers",
    "fintech-landing": "customers comparing trusted financial products",
    "mobile-app-landing": "mobile-first consumers",
    "admin-dashboard": "operators, analysts, and internal teams",
    generic: "website visitors",
  };

  return audiences[websiteType];
}

function parseGeneration(text: string) {
  const cleaned = text
    .trim()
    .replace(/^```json\s*/i, "")
    .replace(/^```\s*/i, "")
    .replace(/\s*```$/i, "");

  const jsonStart = cleaned.indexOf("{");
  const jsonEnd = cleaned.lastIndexOf("}");
  const jsonText = jsonStart >= 0 && jsonEnd > jsonStart ? cleaned.slice(jsonStart, jsonEnd + 1) : cleaned;
  const parsed = generationSchema.safeParse(JSON.parse(jsonText));

  if (!parsed.success) {
    throw new Error("AI provider returned code in an unexpected format. Please try again.");
  }

  return parsed.data;
}

function getCloneGuidance(prompt: string) {
  const normalizedPrompt = prompt.toLowerCase();

  if (!normalizedPrompt.includes("clone")) {
    return "";
  }

  if (normalizedPrompt.includes("youtube")) {
    return [
      "Specific YouTube clone requirements:",
      "- Build a faithful YouTube-style UI, not a renamed alternative brand.",
      "- Visible brand should be YouTube unless the user asks for a different name.",
      "- Include a sticky top bar with menu, YouTube wordmark area, centered search, voice/action icons, and user avatar.",
      "- Include a left navigation rail/sidebar with Home, Shorts, Subscriptions, Library/History-style items.",
      "- Include category chips, a dense responsive video grid, thumbnail blocks, durations, channel avatars, titles, channel names, views, and upload age.",
      "- Use dark or light YouTube-like surfaces intentionally, with strong contrast and no broken image icons.",
      "- On mobile, collapse the sidebar and keep the feed/search experience usable.",
    ].join("\n");
  }

  if (normalizedPrompt.includes("twitter") || /\bx clone\b/.test(normalizedPrompt) || normalizedPrompt.includes("tweet")) {
    return [
      "Specific Twitter/X clone requirements:",
      "- Build a recognizable Twitter/X-style social dashboard, not a generic landing page.",
      "- Use a three-column desktop layout: left navigation, center timeline, right trends/who-to-follow panel.",
      "- Include a composer with avatar, audience controls, media/action buttons, and a primary post button.",
      "- Include at least 8 realistic posts with names, handles, timestamps, post text, optional media-like cards, reply/repost/like/view counts, and hover states.",
      "- Include trending topics, who-to-follow suggestions, sticky navigation behavior, and mobile bottom tabs.",
      "- Use dense but readable spacing, dark or light social app surfaces, clear separators, and realistic microcopy.",
    ].join("\n");
  }

  if (normalizedPrompt.includes("facebook")) {
    return [
      "Specific Facebook clone requirements:",
      "- Build a recognizable Facebook-style social home feed, not a generic landing page.",
      "- Include a top navigation bar with search, tabs, action buttons, and profile controls.",
      "- Include a left shortcuts/sidebar column, central story row/composer/feed, and right contacts/sponsored/trending column on desktop.",
      "- Include at least 8 realistic posts, reactions, comments, share actions, story cards, group/page suggestions, and responsive mobile stacking.",
    ].join("\n");
  }

  return "Clone request requirement: preserve the recognizable identity and interaction pattern of the requested product instead of inventing a generic renamed version.";
}

function serializeFilesForPrompt(files: Array<{ path: string; content: string }>) {
  const importantFiles = files
    .filter((file) =>
      [
        "package.json",
        "index.html",
        "src/main.jsx",
        "src/App.jsx",
        "src/index.css",
        "tailwind.config.js",
        "postcss.config.js",
        "README.md",
      ].includes(file.path),
    )
    .slice(0, 10);

  if (importantFiles.length === 0) {
    return "No files available.";
  }

  return importantFiles
    .map((file) => `--- ${file.path} ---\n${truncateForPrompt(file.content, 12000)}`)
    .join("\n\n");
}

function truncateForPrompt(value: string, maxLength: number) {
  if (value.length <= maxLength) {
    return value;
  }

  return `${value.slice(0, maxLength)}\n...[truncated]`;
}

function getAiProvider(): AiProvider {
  return process.env.AI_PROVIDER?.trim().toLowerCase() === "openrouter" ? "openrouter" : "gemini";
}

function isTemporaryAiError(status: number | undefined, message: string) {
  const lowerMessage = message.toLowerCase();
  return (
    status === 429 ||
    status === 500 ||
    status === 502 ||
    status === 503 ||
    status === 504 ||
    lowerMessage.includes("high demand") ||
    lowerMessage.includes("overloaded") ||
    lowerMessage.includes("rate limit") ||
    lowerMessage.includes("quota") ||
    lowerMessage.includes("temporarily") ||
    lowerMessage.includes("try again later") ||
    lowerMessage.includes("unavailable")
  );
}

async function fetchWithTimeout(url: string, init: RequestInit) {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), aiRequestTimeoutMs);

  try {
    return await fetch(url, { ...init, signal: controller.signal });
  } finally {
    clearTimeout(timeout);
  }
}

function wait(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
